name: Deploy to GitHub Pages

on:
  deployment:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - 
        name: Update the status in_progress
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Start to deploy.
          state: in_progress
          token: "${{ github.token }}"
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
          cache: npm

      - name: Build website
        run: |
          npm install --frozen-lockfile
          npm build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./build
          # TODO: Uncomment the cname field
          # cname: www.gitploy.io
          # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - 
        name: Deploy successfully
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Finish to deploy successfully.
          state: "success"
          token: "${{ github.token }}"
      - 
        name: Deploy failed
        if: failure() || cancelled() 
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Failed to deploy.
          state: "failure"
          token: "${{ github.token }}"