name: Test deployment

on:
  pull_request:

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
          cache: npm
      - 
        name: Test build
        run: | 
          npm install --frozen-lockfile
          npm run build